#!/bin/bash /etc/rc.common
START=99

run_autoupdate()
{
	local enable week minute hour
	config_get_bool enable $1 enable
	config_get_bool enable_proxy $1 enable_proxy
	config_get_bool force_write $1 force_write
	if [[ $enable == 1 ]]; then
		config_get week $1 week
		config_get minute $1 minute
		config_get hour $1 hour
		[[ $week == 7 ]] && week="*"
		bash /bin/AutoUpdate.sh --corn-rm
		[[ $enable_proxy == 1 ]] && task="bash /bin/AutoUpdate.sh -u -P" || task="bash /bin/AutoUpdate.sh -u"
		[[ $force_write == 1 ]] && {
			echo -e "\n$minute $hour * * $week $task -F" >> /etc/crontabs/root
		} || {
			echo -e "\n$minute $hour * * $week $task" >> /etc/crontabs/root
		}
	else
		bash /bin/AutoUpdate.sh --corn-rm
	fi
	if [ -f /bin/AutoUpdate.sh ];then
		custom_github_url="$(uci get autoupdate.@common[0].github)"
		bash /bin/AutoUpdate.sh -C ${custom_github_url}
	fi
	/etc/init.d/cron restart
}

start()
{
	config_load autoupdate
	config_foreach run_autoupdate common
}

stop()
{
	bash /bin/AutoUpdate.sh --corn-rm >/dev/null 2>&1
	bash /bin/AutoUpdate.sh --clean >/dev/null 2>&1
}

restart()
{
	stop
	start
}